#TODO: Rename this to serde-object.
[package]
name = "serde-object"
version = "0.0.0-dev"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cast = { version = "0.2.3", features = ["x128"] }
lazy_static = "1.4.0"
serde = "1.0.114"
wyz = "0.2.0"
